[build]
  publish = "."

[[redirects]]
  from = "/onpoint"
  to = "/onpoint.html"
  status = 200

[[redirects]]
  from = "/onpoint/scroll"
  to = "/onpoint.html?mode=scroll"
  status = 302

[[redirects]]
  from = "/onpoint/slide"
  to = "/onpoint.html?mode=slide"
  status = 302

[[redirects]]
  from = "/integrity/scroll"
  to = "/integrity.html?mode=scroll"
  status = 302

[[redirects]]
  from = "/fountainlife/scroll"
  to = "/fountainlife.html?mode=scroll"
  status = 302

[[redirects]]
  from = "/integrity"
  to = "/integrity.html"
  status = 200

[[redirects]]
  from = "/fountainlife"
  to = "/fountainlife.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=0, must-revalidate"
